// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	cartItemsFieldNames          = builder.RawFieldNames(&CartItems{})
	cartItemsRows                = strings.Join(cartItemsFieldNames, ",")
	cartItemsRowsExpectAutoSet   = strings.Join(stringx.Remove(cartItemsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	cartItemsRowsWithPlaceHolder = strings.Join(stringx.Remove(cartItemsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	cartItemsModel interface {
		Insert(ctx context.Context, data *CartItems) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*CartItems, error)
		FindOneByUserIdSkuId(ctx context.Context, userId uint64, skuId uint64) (*CartItems, error)
		Update(ctx context.Context, data *CartItems) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultCartItemsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CartItems struct {
		Id          uint64         `db:"id"`           // è´­ç‰©è½¦é¡¹ID
		UserId      uint64         `db:"user_id"`      // ç”¨æˆ·ID
		ProductId   uint64         `db:"product_id"`   // å•†å“ID
		SkuId       uint64         `db:"sku_id"`       // SKU ID
		ProductName string         `db:"product_name"` // å•†å“åç§°
		SkuName     string         `db:"sku_name"`     // SKUåç§°
		Image       sql.NullString `db:"image"`        // å•†å“å›¾ç‰‡
		Price       float64        `db:"price"`        // å•†å“å•ä»·
		Quantity    int64          `db:"quantity"`     // å•†å“æ•°é‡
		Selected    int64          `db:"selected"`     // æ˜¯å¦é€‰ä¸­
		CreatedAt   time.Time      `db:"created_at"`   // åˆ›å»ºæ—¶é—´
		UpdatedAt   time.Time      `db:"updated_at"`   // æ›´æ–°æ—¶é—´
	}
)

func newCartItemsModel(conn sqlx.SqlConn) *defaultCartItemsModel {
	return &defaultCartItemsModel{
		conn:  conn,
		table: "`cart_items`",
	}
}

func (m *defaultCartItemsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCartItemsModel) FindOne(ctx context.Context, id uint64) (*CartItems, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cartItemsRows, m.table)
	var resp CartItems
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCartItemsModel) FindOneByUserIdSkuId(ctx context.Context, userId uint64, skuId uint64) (*CartItems, error) {
	var resp CartItems
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `sku_id` = ? limit 1", cartItemsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, skuId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCartItemsModel) Insert(ctx context.Context, data *CartItems) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, cartItemsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.ProductId, data.SkuId, data.ProductName, data.SkuName, data.Image, data.Price, data.Quantity, data.Selected)
	return ret, err
}

func (m *defaultCartItemsModel) Update(ctx context.Context, newData *CartItems) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, cartItemsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.ProductId, newData.SkuId, newData.ProductName, newData.SkuName, newData.Image, newData.Price, newData.Quantity, newData.Selected, newData.Id)
	return err
}

func (m *defaultCartItemsModel) tableName() string {
	return m.table
}
