// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	orderItemsFieldNames          = builder.RawFieldNames(&OrderItems{})
	orderItemsRows                = strings.Join(orderItemsFieldNames, ",")
	orderItemsRowsExpectAutoSet   = strings.Join(stringx.Remove(orderItemsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	orderItemsRowsWithPlaceHolder = strings.Join(stringx.Remove(orderItemsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	orderItemsModel interface {
		Insert(ctx context.Context, data *OrderItems) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*OrderItems, error)
		Update(ctx context.Context, data *OrderItems) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultOrderItemsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	OrderItems struct {
		Id          uint64    `db:"id"`           // è®¢å•é¡¹ID
		OrderId     uint64    `db:"order_id"`     // è®¢å•ID
		ProductId   uint64    `db:"product_id"`   // å•†å“ID
		SkuId       uint64    `db:"sku_id"`       // SKU ID
		ProductName string    `db:"product_name"` // å•†å“åç§°
		SkuName     string    `db:"sku_name"`     // SKUåç§°
		Price       float64   `db:"price"`        // å•†å“å•ä»·
		Quantity    int64     `db:"quantity"`     // è´­ä¹°æ•°é‡
		TotalAmount float64   `db:"total_amount"` // æ€»é‡‘é¢
		CreatedAt   time.Time `db:"created_at"`   // åˆ›å»ºæ—¶é—´
	}
)

func newOrderItemsModel(conn sqlx.SqlConn) *defaultOrderItemsModel {
	return &defaultOrderItemsModel{
		conn:  conn,
		table: "`order_items`",
	}
}

func (m *defaultOrderItemsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultOrderItemsModel) FindOne(ctx context.Context, id uint64) (*OrderItems, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", orderItemsRows, m.table)
	var resp OrderItems
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOrderItemsModel) Insert(ctx context.Context, data *OrderItems) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, orderItemsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.OrderId, data.ProductId, data.SkuId, data.ProductName, data.SkuName, data.Price, data.Quantity, data.TotalAmount)
	return ret, err
}

func (m *defaultOrderItemsModel) Update(ctx context.Context, data *OrderItems) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, orderItemsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.OrderId, data.ProductId, data.SkuId, data.ProductName, data.SkuName, data.Price, data.Quantity, data.TotalAmount, data.Id)
	return err
}

func (m *defaultOrderItemsModel) tableName() string {
	return m.table
}
