// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	stockLocksFieldNames          = builder.RawFieldNames(&StockLocks{})
	stockLocksRows                = strings.Join(stockLocksFieldNames, ",")
	stockLocksRowsExpectAutoSet   = strings.Join(stringx.Remove(stockLocksFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	stockLocksRowsWithPlaceHolder = strings.Join(stringx.Remove(stockLocksFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	stockLocksModel interface {
		Insert(ctx context.Context, data *StockLocks) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*StockLocks, error)
		FindOneByOrderNoSkuId(ctx context.Context, orderNo string, skuId uint64) (*StockLocks, error)
		Update(ctx context.Context, data *StockLocks) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultStockLocksModel struct {
		conn  sqlx.SqlConn
		table string
	}

	StockLocks struct {
		Id          uint64    `db:"id"`           // é”å®šID
		OrderNo     string    `db:"order_no"`     // è®¢å•å·
		SkuId       uint64    `db:"sku_id"`       // SKU ID
		WarehouseId uint64    `db:"warehouse_id"` // ä»“åº“ID
		Quantity    int64     `db:"quantity"`     // é”å®šæ•°é‡
		Status      int64     `db:"status"`       // çŠ¶æ€ 1:é”å®š 2:å·²è§£é” 3:å·²æ‰£å‡
		CreatedAt   time.Time `db:"created_at"`   // åˆ›å»ºæ—¶é—´
		UpdatedAt   time.Time `db:"updated_at"`   // æ›´æ–°æ—¶é—´
	}
)

func newStockLocksModel(conn sqlx.SqlConn) *defaultStockLocksModel {
	return &defaultStockLocksModel{
		conn:  conn,
		table: "`stock_locks`",
	}
}

func (m *defaultStockLocksModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultStockLocksModel) FindOne(ctx context.Context, id uint64) (*StockLocks, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", stockLocksRows, m.table)
	var resp StockLocks
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStockLocksModel) FindOneByOrderNoSkuId(ctx context.Context, orderNo string, skuId uint64) (*StockLocks, error) {
	var resp StockLocks
	query := fmt.Sprintf("select %s from %s where `order_no` = ? and `sku_id` = ? limit 1", stockLocksRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, orderNo, skuId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStockLocksModel) Insert(ctx context.Context, data *StockLocks) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, stockLocksRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.OrderNo, data.SkuId, data.WarehouseId, data.Quantity, data.Status)
	return ret, err
}

func (m *defaultStockLocksModel) Update(ctx context.Context, newData *StockLocks) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, stockLocksRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.OrderNo, newData.SkuId, newData.WarehouseId, newData.Quantity, newData.Status, newData.Id)
	return err
}

func (m *defaultStockLocksModel) tableName() string {
	return m.table
}
