Name: inventory.rmq
ListenOn: 0.0.0.0:9085

MessageRpc:
  Etcd:
    Hosts:
    - 127.0.0.1:2379
    Key: message.rpc
  NonBlock: true
  Timeout: 5000

InventoryRpc:
  Etcd:
    Hosts:
    - 127.0.0.1:2379
    Key: inventory.rpc
  NonBlock: true
  Timeout: 5000

# ... existing RabbitMQ config ...

RabbitMQ:
  Host: localhost
  Port: 5672
  Username: guest
  Password: guest
  VHost: /
  Exchanges:
    InventoryEvent:
      Name: inventory.events
      Type: topic
      Durable: true
  Queues:
    StockUpdate:
      Name: inventory.stock.update
      RoutingKey: stock.#
      Durable: true
    StockAlert:
      Name: inventory.stock.alert
      RoutingKey: alert.#
      Durable: true
    StockLock:
      Name: inventory.stock.lock
      RoutingKey: lock.#
      Durable: true
    OrderEvents:
      Name: inventory.order.events
      RoutingKey: order.*
      Durable: true
  Retry:
    MaxAttempts: 3
    InitialInterval: 1000
    MaxInterval: 10000
    BackoffFactor: 2.0
    Jitter: true
  Batch:
    Size: 100
    FlushInterval: 1000
    Workers: 5
  DeadLetter:
    Exchange: inventory.deadletter
    Queue: inventory.deadletter.queue
    RoutingKey: deadletter
  Middleware:
    EnableRecovery: true
    EnableLogging: true
  Server:
    Name: inventory.rmq
    Mode: standalone
    LogLevel: info
    Consumers:
      - Queue: inventory.stock.update
        Workers: 5
      - Queue: inventory.stock.alert
        Workers: 3
      - Queue: inventory.stock.lock
        Workers: 5
      - Queue: inventory.order.events
        Workers: 5
    Monitor:
      Enabled: true
      Port: 9086

Etcd:
  Hosts:
    - 127.0.0.1:2379
  Key: inventory.rmq