Name: inventory.rmq
ListenOn: 0.0.0.0:9085

Mysql:
  DataSource: root:pa55word@tcp(localhost:3306)/mall_inventory?parseTime=true&loc=Local&charset=utf8mb4&collation=utf8mb4_unicode_ci

CacheRedis:
  - Host: localhost:6379
    Pass: 
    Type: node

RabbitMQ:
  Host: localhost
  Port: 5672
  Username: guest
  Password: guest
  VHost: /
  ConnectionTimeout: 10
  HeartbeatInterval: 10
  PrefetchCount: 1
  PrefetchGlobal: false

  # Exchange definitions
  Exchanges:
    - Name: inventory.events
      Type: topic
      Durable: true
      AutoDelete: false
      Internal: false
      NoWait: false
    # Add payment events exchange
    - Name: payment.events
      Type: topic  
      Durable: true
      AutoDelete: false
      Internal: false
      NoWait: false

  # Queue definitions  
  Queues:
    - Name: stock.update
      Durable: true
      AutoDelete: false
      Exclusive: false
      NoWait: false
      Bindings:
        - Exchange: inventory.events
          RoutingKey: inventory.stock.update.*
          NoWait: false

    - Name: stock.alert
      Durable: true
      AutoDelete: false
      Exclusive: false
      NoWait: false
      Bindings:
        - Exchange: inventory.events
          RoutingKey: inventory.stock.alert.*
          NoWait: false
    
    - Name: stock.lock
      Durable: true
      AutoDelete: false
      Exclusive: false
      NoWait: false
      Bindings:
        - Exchange: inventory.events
          RoutingKey: inventory.stock.lock.*
          NoWait: false

    - Name: order.events
      Durable: true
      AutoDelete: false
      Exclusive: false
      NoWait: false
      Bindings:
        - Exchange: order.events
          RoutingKey: order.*
          NoWait: false

    # Add payment success queue
    - Name: inventory.payment.success
      Durable: true
      AutoDelete: false 
      Exclusive: false
      NoWait: false
      Bindings:
        - Exchange: payment.events
          RoutingKey: payment.success
          NoWait: false

    # Add payment failed queue  
    - Name: inventory.payment.failed
      Durable: true
      AutoDelete: false
      Exclusive: false 
      NoWait: false
      Bindings:
        - Exchange: payment.events
          RoutingKey: payment.failed
          NoWait: false

Log:
  ServiceName: inventory-rmq
  Mode: file
  Path: logs
  Level: info
  Compress: false
  KeepDays: 7

Prometheus:
  Host: 0.0.0.0
  Port: 9184
  Path: /metrics

Telemetry:
  Name: inventory.rmq
  Endpoint: http://127.0.0.1:14268/api/traces
  Sampler: 1.0
  Batcher: jaeger

Etcd:
  Hosts:
    - 127.0.0.1:2379
  Key: inventory.rmq