FROM golang:1.23.4

WORKDIR /go/src/app

# Copy the entire project
COPY ../. .

# Set working directory to user service
WORKDIR /go/src/app/ecommerce/user

# Pre-download dependencies
RUN go mod download

CMD ["go", "test", "-v", "./rpc/internal/logic/gettransaction_test.go", "./rpc/internal/logic/gettransactionslogic.go"]