// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.4

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	paymentChannelsFieldNames          = builder.RawFieldNames(&PaymentChannels{})
	paymentChannelsRows                = strings.Join(paymentChannelsFieldNames, ",")
	paymentChannelsRowsExpectAutoSet   = strings.Join(stringx.Remove(paymentChannelsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	paymentChannelsRowsWithPlaceHolder = strings.Join(stringx.Remove(paymentChannelsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheMallPaymentPaymentChannelsIdPrefix      = "cache:mallPayment:paymentChannels:id:"
	cacheMallPaymentPaymentChannelsChannelPrefix = "cache:mallPayment:paymentChannels:channel:"
)

type (
	paymentChannelsModel interface {
		Insert(ctx context.Context, data *PaymentChannels) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*PaymentChannels, error)
		FindOneByChannel(ctx context.Context, channel int64) (*PaymentChannels, error)
		Update(ctx context.Context, data *PaymentChannels) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultPaymentChannelsModel struct {
		sqlc.CachedConn
		table string
	}

	PaymentChannels struct {
		Id        uint64    `db:"id"`         // è‡ªå¢žID
		Name      string    `db:"name"`       // æ¸ é“åç§°
		Channel   int64     `db:"channel"`    // æ¸ é“ç±»åž‹ 1:å¾®ä¿¡ 2:æ”¯ä»˜å®
		Config    string    `db:"config"`     // æ¸ é“é…ç½®
		Status    int64     `db:"status"`     // çŠ¶æ€ 1:å¯ç”¨ 2:ç¦ç”¨
		CreatedAt time.Time `db:"created_at"` // åˆ›å»ºæ—¶é—´
		UpdatedAt time.Time `db:"updated_at"` // æ›´æ–°æ—¶é—´
	}
)

func newPaymentChannelsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPaymentChannelsModel {
	return &defaultPaymentChannelsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`payment_channels`",
	}
}

func (m *defaultPaymentChannelsModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	mallPaymentPaymentChannelsChannelKey := fmt.Sprintf("%s%v", cacheMallPaymentPaymentChannelsChannelPrefix, data.Channel)
	mallPaymentPaymentChannelsIdKey := fmt.Sprintf("%s%v", cacheMallPaymentPaymentChannelsIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, mallPaymentPaymentChannelsChannelKey, mallPaymentPaymentChannelsIdKey)
	return err
}

func (m *defaultPaymentChannelsModel) FindOne(ctx context.Context, id uint64) (*PaymentChannels, error) {
	mallPaymentPaymentChannelsIdKey := fmt.Sprintf("%s%v", cacheMallPaymentPaymentChannelsIdPrefix, id)
	var resp PaymentChannels
	err := m.QueryRowCtx(ctx, &resp, mallPaymentPaymentChannelsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", paymentChannelsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPaymentChannelsModel) FindOneByChannel(ctx context.Context, channel int64) (*PaymentChannels, error) {
	mallPaymentPaymentChannelsChannelKey := fmt.Sprintf("%s%v", cacheMallPaymentPaymentChannelsChannelPrefix, channel)
	var resp PaymentChannels
	err := m.QueryRowIndexCtx(ctx, &resp, mallPaymentPaymentChannelsChannelKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `channel` = ? limit 1", paymentChannelsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, channel); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPaymentChannelsModel) Insert(ctx context.Context, data *PaymentChannels) (sql.Result, error) {
	mallPaymentPaymentChannelsChannelKey := fmt.Sprintf("%s%v", cacheMallPaymentPaymentChannelsChannelPrefix, data.Channel)
	mallPaymentPaymentChannelsIdKey := fmt.Sprintf("%s%v", cacheMallPaymentPaymentChannelsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, paymentChannelsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.Channel, data.Config, data.Status)
	}, mallPaymentPaymentChannelsChannelKey, mallPaymentPaymentChannelsIdKey)
	return ret, err
}

func (m *defaultPaymentChannelsModel) Update(ctx context.Context, newData *PaymentChannels) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	mallPaymentPaymentChannelsChannelKey := fmt.Sprintf("%s%v", cacheMallPaymentPaymentChannelsChannelPrefix, data.Channel)
	mallPaymentPaymentChannelsIdKey := fmt.Sprintf("%s%v", cacheMallPaymentPaymentChannelsIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, paymentChannelsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.Channel, newData.Config, newData.Status, newData.Id)
	}, mallPaymentPaymentChannelsChannelKey, mallPaymentPaymentChannelsIdKey)
	return err
}

func (m *defaultPaymentChannelsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheMallPaymentPaymentChannelsIdPrefix, primary)
}

func (m *defaultPaymentChannelsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", paymentChannelsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPaymentChannelsModel) tableName() string {
	return m.table
}
