// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	messageTemplatesFieldNames          = builder.RawFieldNames(&MessageTemplates{})
	messageTemplatesRows                = strings.Join(messageTemplatesFieldNames, ",")
	messageTemplatesRowsExpectAutoSet   = strings.Join(stringx.Remove(messageTemplatesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	messageTemplatesRowsWithPlaceHolder = strings.Join(stringx.Remove(messageTemplatesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	messageTemplatesModel interface {
		Insert(ctx context.Context, data *MessageTemplates) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*MessageTemplates, error)
		FindOneByCode(ctx context.Context, code string) (*MessageTemplates, error)
		Update(ctx context.Context, data *MessageTemplates) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultMessageTemplatesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	MessageTemplates struct {
		Id              uint64         `db:"id"`               // æ¨¡æ¿ID
		Code            string         `db:"code"`             // æ¨¡æ¿ç¼–ç 
		Name            string         `db:"name"`             // æ¨¡æ¿åç§°
		TitleTemplate   string         `db:"title_template"`   // æ ‡é¢˜æ¨¡æ¿
		ContentTemplate string         `db:"content_template"` // å†…å®¹æ¨¡æ¿
		Type            int64          `db:"type"`             // æ¶ˆæ¯ç±»åž‹
		Channels        string         `db:"channels"`         // å‘é€æ¸ é“
		Config          sql.NullString `db:"config"`           // æ¸ é“é…ç½®
		Status          int64          `db:"status"`           // çŠ¶æ€ 1:å¯ç”¨ 2:ç¦ç”¨
		CreatedAt       time.Time      `db:"created_at"`       // åˆ›å»ºæ—¶é—´
		UpdatedAt       time.Time      `db:"updated_at"`       // æ›´æ–°æ—¶é—´
	}
)

func newMessageTemplatesModel(conn sqlx.SqlConn) *defaultMessageTemplatesModel {
	return &defaultMessageTemplatesModel{
		conn:  conn,
		table: "`message_templates`",
	}
}

func (m *defaultMessageTemplatesModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultMessageTemplatesModel) FindOne(ctx context.Context, id uint64) (*MessageTemplates, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", messageTemplatesRows, m.table)
	var resp MessageTemplates
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMessageTemplatesModel) FindOneByCode(ctx context.Context, code string) (*MessageTemplates, error) {
	var resp MessageTemplates
	query := fmt.Sprintf("select %s from %s where `code` = ? limit 1", messageTemplatesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, code)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMessageTemplatesModel) Insert(ctx context.Context, data *MessageTemplates) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, messageTemplatesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Code, data.Name, data.TitleTemplate, data.ContentTemplate, data.Type, data.Channels, data.Config, data.Status)
	return ret, err
}

func (m *defaultMessageTemplatesModel) Update(ctx context.Context, newData *MessageTemplates) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, messageTemplatesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Code, newData.Name, newData.TitleTemplate, newData.ContentTemplate, newData.Type, newData.Channels, newData.Config, newData.Status, newData.Id)
	return err
}

func (m *defaultMessageTemplatesModel) tableName() string {
	return m.table
}
