Name: inventory.rpc
ListenOn: 0.0.0.0:8085

Mysql:
  DataSource: root:pa55word@tcp(localhost:3306)/mall_inventory?parseTime=true&loc=Local&charset=utf8mb4&collation=utf8mb4_unicode_ci

CacheRedis:
  - Host: localhost:6379
    Pass: 
    Type: node

RabbitMQ:
  Host: localhost
  Port: 5672
  Username: guest
  Password: guest
  VHost: /
  Exchange: inventory.events
  ConnectionTimeout: 10
  HeartbeatInterval: 10

# Inventory specific settings
StockLockTimeout: 1800    # Stock lock timeout in seconds (30 minutes)
MaxBatchSize: 100         # Maximum items in batch operations
AlertThreshold: 10        # Low stock alert threshold
DefaultWarehouseId: 1     # Default warehouse ID
DefaultPageSize: 20       # Default page size for listings

Log:
  ServiceName: inventory-rpc
  Mode: file
  Path: logs
  Level: info
  Compress: false
  KeepDays: 7

Prometheus:
  Host: 0.0.0.0
  Port: 9085
  Path: /metrics

Telemetry:
  Name: inventory.rpc
  Endpoint: http://127.0.0.1:14268/api/traces
  Sampler: 1.0
  Batcher: jaeger

MessageRpc:
  Etcd:
    Hosts:
      - 127.0.0.1:2379
    Key: message.rpc

Etcd:
  Hosts:
    - 127.0.0.1:2379
  Key: inventory.rpc